In [1]:
import re, ftfy

def read_github_csv(url, encoding="latin1"):
    import requests
    from io import StringIO
    import pandas as pd
    
    text = requests.get(url).content.decode(encoding)
    return pd.read_csv(StringIO(text))

In [2]:


url = "https://raw.githubusercontent.com/okkyibrohim/id-multi-label-hate-speech-and-abusive-language-detection/master/re_dataset.csv"

df = read_github_csv(url)
df

,Tweet,HS,Abusive,HS_Individual,HS_Group,HS_Religion,HS_Race,HS_Physical,HS_Gender,HS_Other,HS_Weak,HS_Moderate,HS_Strong
0,- disaat semua cowok berusaha melacak perhatia...,1,1,1,0,0,0,0,0,1,1,0,0
1,RT USER: USER siapa yang telat ngasih tau elu?...,0,1,0,0,0,0,0,0,0,0,0,0
2,"41. Kadang aku berfikir, kenapa aku tetap perc...",0,0,0,0,0,0,0,0,0,0,0,0
3,USER USER AKU ITU AKU\n\nKU TAU MATAMU SIPIT T...,0,0,0,0,0,0,0,0,0,0,0,0
4,USER USER Kaum cebong kapir udah keliatan dong...,1,1,0,1,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13164,USER jangan asal ngomong ndasmu. congor lu yg ...,1,1,1,0,0,0,1,0,0,1,0,0
13165,USER Kasur mana enak kunyuk',0,1,0,0,0,0,0,0,0,0,0,0
13166,USER Hati hati bisu :( .g\n\nlagi bosan huft \...,0,0,0,0,0,0,0,0,0,0,0,0
13167,USER USER USER USER Bom yang real mudah terdet...,0,0,0,0,0,0,0,0,0,0,0,0
13168,"USER Mana situ ngasih("": itu cuma foto ya kuti...",1,1,1,0,0,0,0,0,1,1,0,0

### Text Cleaning

In [3]:
def fix_text(text):
    return ftfy.fix_text(text)

def remove_newline(text):
    return text.replace("\n", " ")

def remove_emoji(text):
    emoji_pattern = re.compile("[" 
        u"\U0001F600-\U0001F64F"
        u"\U0001F300-\U0001F5FF"
        u"\U0001F680-\U0001F6FF"
        u"\U0001F1E0-\U0001F1FF"
        "]+", flags=re.UNICODE)
    return emoji_pattern.sub("", text)

def remove_hex_emoji(text):
    # Hapus pola emoji hex seperti \xf0\x9f\x98\x84
    text = re.sub(r"\\x[a-fA-F0-9]{2}", " ", text)
    text = re.sub(r"x[a-fA-F0-9]{2}", " ", text)
    return text

def to_lower(text):
    return text.lower()

def remove_user_url(text):
    text = re.sub(r"\bUSER\b", " ", text)
    text = re.sub(r"\bURL\b", " ", text)
    return text

def remove_rt(text):
    return re.sub(r"\brt\b", " ", text)

def remove_thread_number(text):
    return re.sub(r"^\s*\d+\.\s*", "", text)

def remove_escape_sequences(text):
    text = re.sub(r"\\[nrtvf0]", " ", text)  # hapus \n, \t, \r, dll.
    text = re.sub(r"\bn\b", " ", text)       # hapus 'n' sisa escape literal
    return text

def clean_symbols(text):
    # HAPUS noise, SIMPAN .,!?-
    return re.sub(r"[^0-9a-zA-Z\s.,!?-]", " ", text)

def normalize_whitespace(text):
    return re.sub(r"\s+", " ", text).strip()

# FINAL PIPELINE
def preprocess_text(text):
    text = fix_text(text)
    text = remove_newline(text)
    text = remove_user_url(text)
    text = to_lower(text)
    text = remove_emoji(text)
    text = remove_hex_emoji(text)
    text = remove_rt(text)
    text = remove_thread_number(text)
    text = remove_escape_sequences(text)
    text = clean_symbols(text)
    text = normalize_whitespace(text)
    return text

In [4]:
df["clean_text"] = df["Tweet"].apply(preprocess_text)
df

,Tweet,HS,Abusive,HS_Individual,HS_Group,HS_Religion,HS_Race,HS_Physical,HS_Gender,HS_Other,HS_Weak,HS_Moderate,HS_Strong,clean_text
0,- disaat semua cowok berusaha melacak perhatia...,1,1,1,0,0,0,0,0,1,1,0,0,- disaat semua cowok berusaha melacak perhatia...
1,RT USER: USER siapa yang telat ngasih tau elu?...,0,1,0,0,0,0,0,0,0,0,0,0,siapa yang telat ngasih tau elu?edan sarap gue...
2,"41. Kadang aku berfikir, kenapa aku tetap perc...",0,0,0,0,0,0,0,0,0,0,0,0,"kadang aku berfikir, kenapa aku tetap percaya ..."
3,USER USER AKU ITU AKU\n\nKU TAU MATAMU SIPIT T...,0,0,0,0,0,0,0,0,0,0,0,0,aku itu aku ku tau matamu sipit tapi diliat da...
4,USER USER Kaum cebong kapir udah keliatan dong...,1,1,0,1,1,0,0,0,0,0,1,0,kaum cebong kapir udah keliatan dongoknya dari...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13164,USER jangan asal ngomong ndasmu. congor lu yg ...,1,1,1,0,0,0,1,0,0,1,0,0,jangan asal ngomong ndasmu. congor lu yg sekat...
13165,USER Kasur mana enak kunyuk',0,1,0,0,0,0,0,0,0,0,0,0,kasur mana enak kunyuk
13166,USER Hati hati bisu :( .g\n\nlagi bosan huft \...,0,0,0,0,0,0,0,0,0,0,0,0,hati hati bisu .g lagi bosan huft
13167,USER USER USER USER Bom yang real mudah terdet...,0,0,0,0,0,0,0,0,0,0,0,0,bom yang real mudah terdeteksi bom yang terkub...
13168,"USER Mana situ ngasih("": itu cuma foto ya kuti...",1,1,1,0,0,0,0,0,1,1,0,0,mana situ ngasih itu cuma foto ya kutil onta

### Penanganan Duplikasi Data

In [5]:
df['clean_text'].duplicated().sum()

np.int64(287)

In [6]:
df[df['clean_text'].duplicated(keep='first')]

,Tweet,HS,Abusive,HS_Individual,HS_Group,HS_Religion,HS_Race,HS_Physical,HS_Gender,HS_Other,HS_Weak,HS_Moderate,HS_Strong,clean_text
288,USER USER USER USER USER USER USER USER USER U...,1,1,0,1,0,0,0,0,1,0,1,0,
295,#GubernurZamanNow #GusIpulPuti2 #GanjarYasin1 ...,0,0,0,0,0,0,0,0,0,0,0,0,gubernurzamannow gusipulputi2 ganjaryasin1 dja...
318,USER USER USER USER USER USER USER USER USER U...,0,0,0,0,0,0,0,0,0,0,0,0,
377,USER USER USER USER USER USER USER USER USER U...,0,0,0,0,0,0,0,0,0,0,0,0,
378,#GubernurZamanNow #GusIpulPuti2 #GanjarYasin1 ...,0,0,0,0,0,0,0,0,0,0,0,0,gubernurzamannow gusipulputi2 ganjaryasin1 dja...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13054,nih ya baca tai. udah dong jangan spam minta k...,1,1,1,0,0,0,0,0,1,1,0,0,nih ya baca tai. udah dong jangan spam minta k...
13075,*Bravoo Presiden Jokowi !ð???* Presiden Joko W...,0,0,0,0,0,0,0,0,0,0,0,0,bravoo presiden jokowi ! ??? presiden joko wid...
13085,;Kebanyakan fitnah nih mpok silvy #DebatFinalP...,1,0,1,0,0,0,0,0,1,1,0,0,kebanyakan fitnah nih mpok silvy debatfinalpil...
13087,Ngentot Diatas\nURL,0,1,0,0,0,0,0,0,0,0,0,0,ngentot diatas url
13088,gmw liat dm dr lu ah! udh tau gua nanya tentan...,1,1,1,0,0,0,1,0,0,1,0,0,gmw liat dm dr lu ah! udh tau gua nanya tentan...

In [7]:
df = df.drop_duplicates(subset='clean_text', keep='first')
df

,Tweet,HS,Abusive,HS_Individual,HS_Group,HS_Religion,HS_Race,HS_Physical,HS_Gender,HS_Other,HS_Weak,HS_Moderate,HS_Strong,clean_text
0,- disaat semua cowok berusaha melacak perhatia...,1,1,1,0,0,0,0,0,1,1,0,0,- disaat semua cowok berusaha melacak perhatia...
1,RT USER: USER siapa yang telat ngasih tau elu?...,0,1,0,0,0,0,0,0,0,0,0,0,siapa yang telat ngasih tau elu?edan sarap gue...
2,"41. Kadang aku berfikir, kenapa aku tetap perc...",0,0,0,0,0,0,0,0,0,0,0,0,"kadang aku berfikir, kenapa aku tetap percaya ..."
3,USER USER AKU ITU AKU\n\nKU TAU MATAMU SIPIT T...,0,0,0,0,0,0,0,0,0,0,0,0,aku itu aku ku tau matamu sipit tapi diliat da...
4,USER USER Kaum cebong kapir udah keliatan dong...,1,1,0,1,1,0,0,0,0,0,1,0,kaum cebong kapir udah keliatan dongoknya dari...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13164,USER jangan asal ngomong ndasmu. congor lu yg ...,1,1,1,0,0,0,1,0,0,1,0,0,jangan asal ngomong ndasmu. congor lu yg sekat...
13165,USER Kasur mana enak kunyuk',0,1,0,0,0,0,0,0,0,0,0,0,kasur mana enak kunyuk
13166,USER Hati hati bisu :( .g\n\nlagi bosan huft \...,0,0,0,0,0,0,0,0,0,0,0,0,hati hati bisu .g lagi bosan huft
13167,USER USER USER USER Bom yang real mudah terdet...,0,0,0,0,0,0,0,0,0,0,0,0,bom yang real mudah terdeteksi bom yang terkub...
13168,"USER Mana situ ngasih("": itu cuma foto ya kuti...",1,1,1,0,0,0,0,0,1,1,0,0,mana situ ngasih itu cuma foto ya kutil onta

### Reset Index

In [8]:
df.reset_index(inplace=True, drop=True)
df

,Tweet,HS,Abusive,HS_Individual,HS_Group,HS_Religion,HS_Race,HS_Physical,HS_Gender,HS_Other,HS_Weak,HS_Moderate,HS_Strong,clean_text
0,- disaat semua cowok berusaha melacak perhatia...,1,1,1,0,0,0,0,0,1,1,0,0,- disaat semua cowok berusaha melacak perhatia...
1,RT USER: USER siapa yang telat ngasih tau elu?...,0,1,0,0,0,0,0,0,0,0,0,0,siapa yang telat ngasih tau elu?edan sarap gue...
2,"41. Kadang aku berfikir, kenapa aku tetap perc...",0,0,0,0,0,0,0,0,0,0,0,0,"kadang aku berfikir, kenapa aku tetap percaya ..."
3,USER USER AKU ITU AKU\n\nKU TAU MATAMU SIPIT T...,0,0,0,0,0,0,0,0,0,0,0,0,aku itu aku ku tau matamu sipit tapi diliat da...
4,USER USER Kaum cebong kapir udah keliatan dong...,1,1,0,1,1,0,0,0,0,0,1,0,kaum cebong kapir udah keliatan dongoknya dari...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12877,USER jangan asal ngomong ndasmu. congor lu yg ...,1,1,1,0,0,0,1,0,0,1,0,0,jangan asal ngomong ndasmu. congor lu yg sekat...
12878,USER Kasur mana enak kunyuk',0,1,0,0,0,0,0,0,0,0,0,0,kasur mana enak kunyuk
12879,USER Hati hati bisu :( .g\n\nlagi bosan huft \...,0,0,0,0,0,0,0,0,0,0,0,0,hati hati bisu .g lagi bosan huft
12880,USER USER USER USER Bom yang real mudah terdet...,0,0,0,0,0,0,0,0,0,0,0,0,bom yang real mudah terdeteksi bom yang terkub...
12881,"USER Mana situ ngasih("": itu cuma foto ya kuti...",1,1,1,0,0,0,0,0,1,1,0,0,mana situ ngasih itu cuma foto ya kutil onta

### Slang

In [9]:
alay_df = read_github_csv(
    "https://raw.githubusercontent.com/okkyibrohim/id-multi-label-hate-speech-and-abusive-language-detection/master/new_kamusalay.csv",
    encoding="latin1"
)

# jika hanya 1 kolom, pecah sendiri
if alay_df.shape[1] == 1:
    alay_df = alay_df[0].str.split(",", expand=True)

alay_df.columns = [0, 1]
alay_dict = dict(zip(alay_df[0], alay_df[1]))
alay_dict

{'pakcikdahtua': 'pak cik sudah tua',
 'pakcikmudalagi': 'pak cik muda lagi',
 't3tapjokowi': 'tetap jokowi',
 '3x': 'tiga kali',
 'aamiin': 'amin',
 'aamiinn': 'amin',
 'aamin': 'amin',
 'aammiin': 'amin',
 'abis': 'habis',
 'abisin': 'habiskan',
 'acau': 'kacau',
 'achok': 'ahok',
 'ad': 'ada',
 'adek': 'adik',
 'adl': 'adalah',
 'adlah': 'adalah',
 'adlh': 'adalah',
 'ado': 'ada',
 'aduhh': 'aduh',
 'aer': 'air',
 'afdol': 'afdal',
 'agamaataualqur': 'agama alquran',
 'agm': 'agama',
 'agma': 'agama',
 'ahaha': 'haha',
 'ahahaha': 'haha',
 'ahehehehe': 'hehe',
 'ahir': 'akhir',
 'ahirnya': 'akhirnya',
 'ahk': 'ahok',
 'ahlamdulillah': 'alhamdulillah',
 'ahli2': 'para ahli',
 'ahlusunnah': 'ahlus sunah',
 'ahmaddani': 'ahmad dhani',
 'aho': 'ahok',
 'ahoax': 'ahok',
 'ahoaxx': 'ahok',
 'ahog': 'ahok',
 'ahokataudjarot': 'ahok djarot',
 'ahokbebanijokowi': 'ahok beban jokowi',
 'ahokbtp': 'ahok basuki tjahaja purnama',
 'ahokditolakwarga': 'ahok ditolak warga',
 'ahokdjarot': 'ahok djarot',
 'ahokdjarotterbukti': 'ahok djarot terbukti',
 'ahokers': 'ahoker',
 'ahokfighter': 'ahok pejuang',
 'ahokforpresident': 'ahok for presiden',
 'ahokisthebest': 'ahok terbaik',
 'ahokjarot': 'ahok djarot',
 'ahokk': 'ahok',
 'ahokmasukbui': 'ahok masuk bui',
 'ahokmeskipun': 'ahok meskipun',
 'ahokpositifjadi': 'ahok positif jadi',
 'ahoksatuputaran': 'ahok satu putaran',
 'ahoksemangat': 'ahok semangat',
 'ahoktersangka': 'ahok tersangka',
 'ahokterzhalimi': 'ahok terzalimi',
 'ahoktetap': 'ahok tetap',
 'ahoktidaksendiri': 'ahok tidak sendiri',
 'ahokUSER': 'ahok',
 'ahook': 'ahok',
 'ahox': 'ahok',
 'aing': 'aku',
 'airmata': 'air mata',
 'aiskrim': 'es krim',
 'aj': 'saja',
 'aja': 'saja',
 'ajaa': 'saja',
 'ajah': 'saja',
 'ajalah': 'sajalah',
 'aje': 'saja',
 'ajg': 'anjing',
 'ajh': 'saja',
 'ajib': 'hebat',
 'ajj': 'saja',
 'ak': 'aku',
 'akalakalan': 'akal akalan',
 'akalakaln': 'akal akalan',
 'akankena': 'akan kena',
 'akherat': 'akhirat',
 'akhi': 'saudara',
 'akhirny': 'akhirnya',
 'akhirnyamush': 'akhirnya musuh',
 'akirnya': 'akhirnya',
 'akn': 'akan',
 'akoh': 'aku',
 'aksiaksi1120aksi112020aksi1120': 'aksi aksi',
 'akumuslim': 'aku muslim',
 'akuwa': 'aqua',
 'alahuakbar': 'allahu akbar',
 'alallohu': 'alallahu',
 'alesan': 'alasan',
 'alhamdulilah': 'alhamdulillah',
 'alhamdulillaah': 'alhamdulillah',
 'alhamdullilah': 'alhamdulillah',
 'alhmdllh': 'alhamdulillah',
 'allahuakbar': 'allahu akbar',
 'allahughayatuna': 'allahu ghayatuna',
 'alloh': 'allah',
 'allohu': 'allahu',
 'alqur': 'alquran',
 'ama': 'sama',
 'amaca': 'ah masa',
 'amajing': 'luar biasa',
 'amcaman': 'ancaman',
 'amiin': 'amin',
 'aminn': 'amin',
 'ampe': 'sampai',
 'amriki': 'amerika',
 'amuh': 'kamu',
 'ana': 'saya',
 'anbiarkekinian': 'biar kekinian',
 'ancen': 'memang',
 'ancur': 'hancur',
 'ancuur': 'hancur',
 'ane': 'saya',
 'aneh2': 'aneh aneh',
 'anget': 'hangat',
 'angktpn': 'angkatpun',
 'anjeng': 'anjing',
 'anjg': 'anjing',
 'ank': 'anak',
 'anomaly': 'anomali',
 'antikorupsi': 'anti korupsi',
 'antum': 'kalian',
 'anugrah': 'anugerah',
 'ap': 'apa',
 'apa2': 'apa apa',
 'apaapaan': 'apa apaan',
 'apaapalah': 'apa sajalah',
 'apah': 'apa',
 'apakabar': 'apa kabar',
 'apalg': 'apa lagi',
 'apamaunya': 'apa maunya',
 'apane': 'apanya',
 'apaoun': 'apapun',
 'apasih': 'apa sih',
 'ape': 'apa',
 'apenista': 'penista',
 'aph': 'apa',
 'apk': 'apakah',
 'aplgi': 'apa lagi',
 'apo': 'apa',
 'apose': 'apa sih',
 'apz': 'apa',
 'aq': 'aku',
 'aquh': 'aku',
 'artinx': 'artinya',
 'asek': 'asyik',
 'aseng': 'asing',
 'asew': 'anjing',
 'asik': 'asyik',
 'ask': 'tanya',
 'asline': 'aslinya',
 'assalamualaikumalhamdulillahhasil': 'assalamualaykum alhamdulillah hasil',
 'assalamuallaikum': 'assalamualaykum',
 'asu': 'anjing',
 'asw': 'anjing',
 'asyek': 'asyik',
 'atauatau05atauatau0atauatau0': 'atau',
 'atauatauatau': 'atau',
 'atauatauatau201atauatau201atauatauatau201atauatau': 'atau',
 'atauatauatauatau': 'atau',
 'atauatauatauatauatauatauatauatauatauatau': 'atau',
 'atauem': 'atau',
 'atauhr': 'atau',
 'ataus': 'atau',
 'ati': 'hati',
 'ati2': 'hati hati',
 'atit': 'sakit',
 'ato': 'atau',
 'atribut2': 'atribut atribut',
 'atu': 'satu',
 'atw': 'atau',
 'awkeren': 'keren',
 'awutawutan': 'awut awutan',
 'aya': 'ada',
 'ayang': 'sayang',
 'ayok': 'ayo',
 'ayoo': 'ayo',
 'ayosavepakahok': 'ayo lindungi pak ahok',
 'ayuk': 'ayo',
 'aza': 'saja',
 'azhan': 'azan',
 'babeh': 'ayah',
 'badboy': 'bad boy',
 'badjingan': 'bajingan',
 'bae': 'baik',
 'bagaimnpun': 'bagaimana',
 'bagi2': 'bagi bagi',
 'bagimane': 'bagaimana',
 'bahwasannya': 'bahwasanya',
 'bakalan': 'akan',
 'balaikota': 'balai kota',
 'bales': 'balas',
 'balikin': 'kembalikan',
 'baliq': 'balig',
 'bandarq': 'bandarku',
 'banding2in': 'membanding bandingkan',
 'bandingin': 'bandingkan',
 'banga': 'bangsa',
 'banged': 'banget',
 'bangen': 'banget',
 'bangett': 'banget',
 'bangettt': 'banget',
 'bangke': 'bangkai',
 'bangsag': 'bangsat',
 'bangst': 'bangsat',
 'bantuk': 'bentuk',
 'banun': 'bangun',
 'banyak2': 'perbanyak',
 'banyakin': 'perbanyak',
 'bapake': 'ayahnya',
 'baper': 'bawa perasaan',
 'baryaw': 'sabar ya',
 'baryw': 'sabar ya',
 'baso': 'bakso',
 'basukibtp': 'basuki tjahaja purnama',
 'basukigameover': 'basuki kalah',
 'bat': 'banget',
 'bauu': 'bau',
 'bawak': 'bawa',
 'bay': 'selamat tinggal',
 'bayangin': 'bayangkan',
 'bayaranatausuruhan': 'bayaran atau suruhan',
 'bbrapa': 'beberapa',
 'bbrp': 'beberapa',
 'bc': 'baca',
 'bct': 'bacot',
 'bda': 'beda',
 'bdan': 'badan',
 'bdg': 'bandung',
 'bdn': 'badan',
 'becanda': 'bercanda',
 'bedoa': 'berdoa',
 'bedua': 'berdua',
 'bege': 'bego',
 'bejad': 'bejat',
 'bekel': 'bekal',
 'bekingin': 'lindungi',
 'belaislambelaislambelaislam': 'bela islam',
 'belaquran': 'bela alquran',
 'beliin': 'belikan',
 'belom': 'belum',
 'belon': 'belum',
 'benar2': 'benar benar',
 'bener': 'benar',
 'bener2': 'benar benar',
 'beneran': 'benaran',
 'berantem': 'bertengkar',
 'berdo': 'berdoa',
 'berenti': 'berhenti',
 'berfikir': 'berpikir',
 'bergengam': 'bergenggam',
 'bergoncang': 'berguncang',
 'berindak': 'bertindak',
 'beritadan': 'berita dan',
 'beritain': 'memberitakan',
 'beritany': 'beritanya',
 'beritaterkini': 'berita kini',
 'berkacaberkacanya': 'berkaca kaca',
 'berrti': 'berarti',
 'bersyukrlah': 'bersyukurlah',
 'beruk2': 'beruk beruk',
 'besoq': 'besok',
 'bet': 'banget',
 'bete': 'sebal',
 'betulin': 'betulkan',
 'beud': 'banget',
 'beut': 'banget',
 'bg': 'bagi',
 'bgd': 'banget',
 'bgerak': 'bergerak',
 'bget': 'banget',
 'bgi': 'bagi',
 'bgini': 'begini',
 'bgitu': 'begitu',
 'bgks': 'bungkus',
 'bgm': 'bagaimana',
 'bgmn': 'bagaimana',
 'bgmna': 'bagaimana',
 'bgn': 'bangun',
 'bgni': 'begini',
 'bgntdr': 'bangun tidur',
 'bgs': 'bagus',
 'bgst': 'bangsat',
 'bgt': 'banget',
 'bgtu': 'begitu',
 'bgus': 'bagus',
 'bhay': 'selamat tinggal',
 'bhinekaan': 'bhineka',
 'bhinneka': 'bhineka',
 'bhkan': 'bahkan',
 'bhn': 'bahan',
 'bhong': 'bohong',
 'bhs': 'bahas',
 'bhw': 'bahwa',
 'bhwa': 'bahwa',
 'bhy': 'bahaya',
 'biarin': 'biarkan',
 'biarpn': 'biarpun',
 'bijimane': 'bagaimana',
 'bisenye': 'bisanya',
 'bistu': 'habis itu',
 'bisya': 'bisa',
 'biza': 'bisa',
 'bj': 'baju',
 'bju': 'baju',
 'bk': 'buku',
 'bkan': 'bukan',
 'bkap': 'ayah',
 'bkin': 'bikin',
 'bkl': 'bakal',
 'bkn': 'bukan',
 'bkna': 'bukannya',
 'bkp': 'ayah',
 'bkr': 'bakar',
 'bks': 'bungkus',
 'bl': 'beli',
 'blajar': 'belajar',
 'blakan': 'blak',
 'blg': 'bilang',
 'blh': 'boleh',
 'bli': 'beli',
 'blik': 'balik',
 'blingsatanya': 'belingsatan',
 'bljr': 'belajar',
 'blk': 'balik',
 'blkg': 'belakang',
 'blkng': 'belakang',
 'blkngny': 'belakangnya',
 'blm': 'belum',
 'bln': 'bulan',
 'blng': 'bilang',
 'blngn': 'bilangan',
 'blom': 'belum',
 'blon': 'belum',
 'bloon': 'belum',
 'bls': 'balas',
 'blum': 'belum',
 'blusukan': 'blusuk',
 'bndg': 'bandung',
 'bndr': 'bandar',
 'bner': 'benar',
 'bneran': 'benar',
 'bnget': 'banget',
 'bngks': 'bungkus',
 'bngng': 'bingung',
 'bngsa': 'bangsa',
 'bngt': 'banget',
 'bngun': 'bangun',
 'bnr': 'benar',
 'bnrbnr': 'benar benar',
 'bnrn': 'benaran',
 'bntar': 'sebentar',
 'bntr': 'sebentar',
 'bnyak': 'banyak',
 'bnyk': 'banyak',
 'bnykny': 'banyaknya',
 'bobo': 'tidur',
 'bobok': 'tidur',
 'bodo': 'bodoh',
 'bokap': 'ayah',
 'bokaps': 'ayah',
 'bokapz': 'ayah',
 'bole': 'boleh',
 'boong': 'bohong',
 'bosen': 'bosan',
 'boskuh': 'bosku',
 'boten': 'tidak',
 'bozen': 'bosan',
 'bozn': 'bosan',
 'bp': 'bapak',
 'bpak': 'bapak',
 'bpk': 'bapak',
 'br': 'baru',
 'brani': 'berani',
 'brantas': 'berantas',
 'brapa': 'berapa',
 'brarti': 'berarti',
 'brasa': 'berasa',
 'bravoo': 'bravo',
 'breake': 'istirahat',
 'breaking': 'istirahat',
 'brengsek': 'berengsek',
 'brg': 'barang',
 'brgkt': 'berangkat',
 'brharap': 'berharap',
 'brhsl': 'berhasil',
 'brikut': 'berikut',
 'bringas': 'beringas',
 'brisik': 'berisik',
 'brjln': 'berjalan',
 'brjuang': 'berjuang',
 'brkeliaran': 'berkeliaran',
 'brkfst': 'sarapan',
 'brkpntingan': 'berkepentingan',
 'brkumandang': 'berkumandang',
 'brmslh': 'bermasalah',
 'brngkt': 'berangkat',
 'brp': 'berapa',
 'brpa': 'berapa',
 'brpedoman': 'berpedoman',
 'brrti': 'berarti',
 'brs': 'beres',
 'brsal': 'berasal',
 'brsama': 'bersama',
 'brsamamu': 'bersamamu',
 'brshbt': 'bersahabat',
 'brsm': 'bersama',
 'brtahan': 'bertahan',
 'brthn': 'bertahan',
 'brtmn': 'berteman',
 'bru': 'baru',
 'bruh': 'buruh',
 'bryaw': 'sabar ya',
 'bryw': 'sabar ya',
 'bs': 'bisa',
 'bsa': 'bisa',
 'bsk': 'besok',
 'bsok': 'besok',
 'bsoq': 'besok',
 'bsr': 'besar',
 'bte': 'bosan',
 'btg': 'batang',
 'bth': 'butuh',
 'btl': 'betul',
 'btul': 'betul',
 'btull': 'betul',
 'buad': 'buat',
 'buatapa': 'buat apa',
 'buatin': 'buatkan',
 'bubarin': 'bubarkan',
 'bukabukaan': 'buka bukaan',
 'bukane': 'bukannya',
 'bukn': 'bukan',
 'buktiin': 'buktikan',
 'buktikan': 'buktikan',
 'buktikqn': 'buktikan',
 'bul': 'kibul',
 'bulshit': 'kibul',
 'buryam': 'bubur ayam',
 'buzer': 'buzzer',
 'buzzerahoaxsebarkanhoax': 'buzzer ahok sebar hoaks',
 'buzzerbuzzernya': 'buzzer buzzernya',
 'bw': 'bawa',
 'bwa': 'bawa',
 'bwaanx': 'bawaan',
 'bwh': 'bawah',
 'bwt': 'buat',
 'byak': 'banyak',
 'byk': 'banyak',
 'bynk': 'banyak',
 'byr': 'bayar',
 'bzen': 'bosan',
 'bzn': 'bosan',
 'cabut': 'pergi',
 'cagubnya': 'calon gubernurnya',
 'cahya': 'cahaya',
 'caiank': 'sayang',
 'caiyo': 'semangat',
 'cakep': 'cakap',
 'cantek': 'cantik',
 'capek': 'cape',
 'caturx': 'catur',
 'cayo': 'semangat',
 'cb': 'coba',
 'cecunguk2nya': 'cecunguk cecunguknya',
 'ceheheheh': 'hehe',
 'cekola': 'sekolah',
 'cekolah': 'sekolah',
 'celalaw': 'selalu',
 'celalu': 'selalu',
 'cemen': 'takut',
 'cemplungin': 'mencemplungkan',
 'cemungudh': 'semangat',
 'cemungut': 'semangat',
 'cemunguth': 'semangat',
 'centuryataumuniratauhambalang': 'century munir atau hambalang',
 'cepat2': 'cepat cepat',
 'cepet': 'cepat',
 'ceplas': 'ceplos',
 'ceppat': 'cepat',
 'cewe': 'cewek',
 'ciamik': 'indah',
 'ciap': 'siap',
 'ciayou': 'semangat',
 'cibuq': 'sibuk',
 'cie': 'wah',
 'ciee': 'wah',
 'cini': 'sini',
 'cino': 'cina',
 'citizens': 'warga kota',
 'ciyan': 'kasihan',
 'ciye': 'wah',
 'ciyus': 'serius',
 'ckck': 'wkwk',
 'ckp': 'cukup',
 'ckrg': 'sekarang',
 'ckup': 'cukup',
 'cling': 'bersih',
 'cll': 'selalu',
 'cllu': 'selalu',
 'cllw': 'selalu',
 'cm': 'cuma',
 'cma': 'cuma',
 'cman': 'cuma',
 'cmn': 'cuma',
 'cmpk': 'cempaka',
 'col': 'keren',
 'compares': 'membandingkan',
 'congrats': 'selamat',
 'congratulation': 'selamat',
 'corruptions': 'korupsi',
 'corruptors': 'koruptor',
 'cowo': 'cowok',
 'coz': 'soalnya',
 'cpat': 'cepat',
 'cpe': 'cape',
 'cpee': 'cape',
 'cpet': 'cepat',
 'cpt': 'cepat',
 'cptn': 'cepatan',
 'crt': 'cerita',
 'crying': 'menangis',
 'cs': 'rekan',
 'cth': 'contoh',
 'cukupsatuputaran': 'cukup satu putaran',
 'cuman': 'cuma',
 'cw': 'cewek',
 'cwe': 'cewek',
 'cwo': 'cowok',
 'd': 'di',
 'da': 'dan',
 'dah': 'sudah',
 'dalah': 'adalah',
 'dalem': 'dalam',
 'dann': 'dan',
 'dapa': 'ada apa',
 'dapah': 'ada apa',
 'dapet': 'dapat',
 'dapetin': 'mendapatkan',
 'daripaddatidda': 'dari pada tidak',
 'datangin': 'mendatangi',
 'dateng': 'datang',
 'daut': 'daud',
 'dblg': 'dibilang',
 'dblkng': 'dibelakang',
 'dbls': 'dibalas',
 'dbwt': 'dibuat',
 'dbyr': 'dibayar',
 'ddpn': 'di depan',
 'dduk': 'duduk',
 'de': 'deh',
 'demen': 'suka',
 'democrazy': 'demokrasi gila',
 'demodemo': 'demo demo',
 'demodemonov': 'demo november',
 'denger': 'dengar',
 'dengn': 'dengan',
 'depa': 'depan',
 'des': 'desember',
 'dewadewa': 'dewa dewa',
 'dftr': 'daftar',
 'dg': 'dengan',
 'dgn': 'dengan',
 'dgr': 'dengar',
 'dgrn': 'dengarkan',
 'dh': 'sudah',
 'dhewan': 'dewan',
 'diaa': 'dia',
 'diajakin': 'diajak',
 'dianutny': 'dianutnya',
 'diapain': 'diapakan',
 'dibelakanghari': 'di belakang hari',
 'dibiarin': 'dibiarkan',
 'dibobongin': 'dibodohi',
 'dibodohin': 'dibodohi',
 'dibohongin': 'dibohongi',
 'dibohonginataudibodohin': 'dibohongi atau dibodohi',
 'diboongin': 'dibohongi',
 'dibuatx': 'dibuatnya',
 'dibudigunawankan': 'di budi gunawankan',
 'dicuekin': 'dicueki',
 'didenger': 'didengar',
 'didengerin': 'didengarkan',
 'didiemin': 'didiamkan',
 'didlam': 'di dalam',
 'didzalimi': 'dizalimi',
 'die': 'dia',
 'diem': 'diam',
 'diem2': 'diam diam',
 'digembosin': 'digembosi',
 'diginiin': 'dibeginikan',
 'dijadiin': 'dijadikan',
 'dijatohin': 'dijatuhi',
 'dijdkn': 'dijadikan',
 'dikenyataanya': 'pada kenyataannya',
 'dikirain': 'dikiranya',
 'dikit': 'sedikit',
 'dimance': 'di mana',
 'dimandose': 'di mana sih',
 'dimans': 'dimana',
 'dimonitoring': 'dipantau',
 'dinaikin': 'dinaiki',
 'dinegri': 'di negeri',
 'dipake': 'dipakai',
 'dipemjara': 'di penjara',
 'diperes': 'diperas',
 'dipikirin': 'dipikirkan',
 'dipilkada': 'di pilkada',
 'diprose': 'diproses',
 'dirix': 'dirinya',
 'dirmh': 'di rumah',
 'disalahgunakan': 'disalah gunakan',
 'disamarinda': 'di samarinda',
 'disewotin': 'disewoti',
 'disumpahdisumpahin': 'disumpahi',
 'ditemenin': 'ditemani',
 'ditentukn': 'ditentukan',
 'ditetapknnya': 'ditetapkan',
 'ditrsangkakan': 'ditersangkakan',
 'dittapkn': 'ditetapkan',
 'diyem': 'diam',
 'dizhalimi': 'dizalimi',
 'dizholimi': 'dizalimi',
 'dizolimi': 'dizalimi',
 'djakarta': 'di jakarta',
 'djasatuputaran': 'di satu putaran',
 'djkt': 'di jakarta',
 'djl': 'di jalan',
 'djln': 'di jalan',
 'djmin': 'dijamin',
 'dkat': 'dekat',
 'dket': 'dekat',
 'dkijakarta': 'dki jakarta',
 'dkls': 'di kelas',
 'dkmps': 'di kampus',
 'dkmr': 'di kamar',
 'dkntr': 'di kantor',
 'dksh': 'dikasih',
 'dkt': 'dekat',
 'dl': 'dulu',
 'dlm': 'dalam',
 'dlmnya': 'dalamnya',
 'dlrng': 'dilarang',
 'dlu': 'dulu',
 'dluan': 'duluan',
 'dmana': 'di mana',
 'dmkn': 'dimakan',
 'dmn': 'di mana',
 'dmna': 'di mana',
 'dmnmn': 'di mana mana',
 'dmny': 'di mana',
 'dn': 'dan',
 'dng': 'dengan',
 'dngan': 'dengan',
 'dngar': 'dengar',
 'dnger': 'dengar',
 'dngerin': 'dengarkan',
 'dngn': 'dengan',
 'dngr': 'dengar',
 'doain': 'doakan',
 'doank': 'doang',
 'doi': 'dia',
 'dongok': 'dungu',
 'donlot': 'unduh',
 'dont': 'do not',
 'doyan': 'suka',
 'dp': 'uang muka',
 'dpan': 'depan',
 'dpet': 'dapat',
 'dpk': 'depok',
 'dpkrkn': 'dipikirkan',
 'dpn': 'depan',
 'dpnrmh': 'di depan rumah',
 'dpt': 'dapat',
 'dr': 'dari',
 'drg': 'dokter gigi',
 'drh': 'darah',
 'dri': 'dari',
 'drmh': 'di rumah',
 'drmn': 'dari mana',
 'drpd': 'daripada',
 'drtd': 'dari tadi',
 'drumah': 'di rumah',
 'dsar': 'dasar',
 'dsb': 'dan sebagainya',
 'dsblh': 'di sebelah',
 'dsini': 'di sini',
 'dsklh': 'di sekolah',
 'dsni': 'di sini',
 'dsnii': 'di sini',
 'dst': 'dan seterusnya',
 'dtetapak': 'ditetapkan',
 'dtg': 'datang',
 'dtgn': 'datang',
 'dtgny': 'datangnya',
 'dtmbh': 'di tambah',
 'dtmpt': 'di tempat',
 'dtng': 'datang',
 'dttapkn': 'ditetapkan',
 'dtuntut': 'dituntun',
 'duabelas': 'dua belas',
 'duaduanya': 'dua duanya',
 'duchh': 'aduh',
 'duh': 'aduh',
 'duit2': 'duit duit',
 'dukungahok': 'dukung ahok',
 'dukungfatwa': 'dukung fatwa',
 'dukungfatwamui': 'dukung fatwa mui',
 'duluan': 'lebih dahulu',
 'duluw': 'dahulu',
 'dunk': 'dong',
 'durung': 'belum',
 'dy': 'dia',
 'dya': 'dia',
 'dzolim': 'zalim',
 'dzolimi': 'dizalimi',
 'ea': 'iya',
 'eagles': 'elang',
 'ealah': 'iyalah',
 'ech': 'eh',
 'eehh': 'eh',
 'egak': 'tidak',
 'egh': 'eh',
 'ehh': 'eh',
 'ekong': 'kakek',
 'elech': 'alah',
 'elee': 'alah',
 'elektibilitas': 'elektabilitas',
 'elit': 'elite',
 'elo': 'kamu',
 'elu': 'kamu',
 'eman': 'sayang',
 'emang': 'memang',
 'emangnya': 'memangnya',
 'emank': 'memang',
 'emg': 'memang',
 'emng': 'memang',
 'en': 'dan',
 'ending': 'akhir',
 'endingnya': 'akhirnya',
 'engga': 'tidak',
 'enggak': 'tidak',
 'enjarakanahok': 'penjarakan ahok',
 'enk': 'enak',
 'entar': 'nanti',
 'ente': 'kamu',
 'entee': 'kamu',
 'erti': 'mengerti',
 'esbeye': 'susilo bambang yudhoyono',
 'eskrim': 'es krim',
 'eteb': 'bosan',
 'everythings': 'segalanya',
 'faham': 'paham',
 'fanati': 'fanatik',
 'fb': 'facebook',
 'fcked': 'fuck',
 'fears': 'fear',
 'feb': 'februari',
 'fikir': 'pikir',
 'fikiran': 'pikiran',
 'finah': 'fitnah',
 'follback': 'ikuti',
 'follbek': 'ikuti',
 'followback': 'ikuti',
 'follower': 'pengikut',
 'followers': 'pengikut',
 'freeahok': 'free ahok',
 'futures': 'masa depan',
 'g': 'tidak',
 'ga': 'tidak',
 'gaada': 'tidak ada',
 'gabakal': 'tidak akan',
 'gaberani': 'tidak berani',
 'gabisa': 'tidak bisa',
 'gaboleh': 'tidak boleh',
 'gabut': 'kurang kerjaan',
 'gada': 'tidak ada',
 'gaenak': 'tidak enak',
 'gaikut': 'tidak ikut',
 'gajadi': 'tidak jadi',
 'gajelas': 'tidak jelas',
 'gak': 'tidak',
 'gakuat': 'tidak kuat',
 'gakz': 'tidak',
 'galak2': 'galak galak',
 'galo': 'galau',
 'gamasuk': 'tidak masuk',
 'gamau': 'tidak mau',
 'ganbate': 'semangat',
 'ganyangahok': 'ganyang ahok',
 'ganyangcina': 'ganyang cina',
 'gapake': 'tidak pakai',
 'gapapa': 'tidak apa apa',
 'gapapalah': 'tidak apalah',
 'gapape': 'tidak apa',
 'gapedulisamastatus': 'tidak peduli dengan status',
 'gapernah': 'tidak pernah',
 'gapunya': 'tidak punya',
 'gara2': 'gara gara',
 'garangangarangan': 'garang',
 'garem': 'garam',
 'gasuka': 'tidak suka',
 'gatau': 'tak tau',
 'gataw': 'tak tau',
 'gatel': 'gatal',
 'gausah': 'tidak usah',
 'gawe': 'kerja',
 'gbr': 'gambar',
 'gdg': 'gudang',
 'gece': 'gerak cepat',
 'gelaja': 'gejala',
 'gelarperkarasudahdiumumkan': 'gelar perkara sudah umum',
 'gelik': 'geli',
 'gelo': 'gila',
 'gemes': 'gemas',
 'gengges': 'ganggu',
 'genks': 'geng',
 'gera': 'gerak',
 'gerja': 'gereja',
 'ggl': 'gagal',
 'ghiy': 'lagi',
 'gi': 'lagi',
 'gilak': 'gila',
 'gile': 'gila',
 'gilla': 'gila',
 'gimana': 'bagaimana',
 'gimanapun': 'bagaimanapun',
 'gin': 'begini',
 'ginian': 'beginian',
 'gitu': 'begitu',
 'gituan': 'begitu',
 'gituh': 'begitu',
 'gk': 'tidak',
 'gmana': 'bagaimana',
 'gmbr': 'gambar',
 'gmn': 'bagaimana',
 'gmna': 'bagaimana',
 'gmpg': 'gampang',
 'gmpng': 'gampang',
 'gni': 'begini',
 'gnti': 'ganti',
 'goblog': 'goblok',
 'goblog2in': 'goblok goblokin',
 'going': 'pergi',
 'gonna': 'pergi',
 'gosipin': 'menggosipkan',
 'gov': 'gubernur',
 'governo': 'gubernur',
 'governoor': 'gubernur',
 'governor': 'gubernur',
 'governour': 'gubernur',
 'govt': 'pemerintah',
 'goyangin': 'goyangkan',
 'gpl': 'tidak pakai lama',
 'gpny': 'tidak punya',
 'gpp': 'tidak apa apa',
 'gprnh': 'tidak pernah',
 'gr': 'gede rasa',
 'gr2': 'gara gara',
 'gratisan': 'gratis',
 'gregetan': 'geregetan',
 'gt': 'begitu',
 'gtu': 'begitu',
 'gtw': 'tak tau',
 'gua': 'gue',
 'gub': 'gubernur',
 'gubatauwalkot': 'gubernur atau walikota',
 'gubenur': 'gubernur',
 'guberenur': 'gubernur',
 'guemewek': 'gue mewek',
 'guoblog': 'goblok',
 'gurbenur': 'gubernur',
 'guwe': 'gue',
 'gw': 'gue',
 'gwe': 'gue',
 'gws': 'semoga lekas sembuh',
 'gx': 'tidak',
 'ha': 'apa',
 'habaib': 'habib',
 'hacur': 'hancur',
 'hadeh': 'aduh',
 'hadeuh': 'aduh',
 'hahaha': 'haha',
 'hahahahaha': 'haha',
 'hapal': 'hafal',
 'hape': 'telepon genggam',
 'happening': 'terjadi',
 'haq': 'hak',

In [10]:
# def normalize_slang(text):
#     return " ".join([alay_dict.get(w, w) for w in text.split()])

In [11]:
# df = df.copy()
# df['normalized_comment'] = df['clean_text'].apply(normalize_slang)
# df[['Tweet', 'normalized_comment']].head(50)

In [12]:
import requests

# 1. Loader kamus dari GitHub RAW

def load_dict_from_github(url):
    d = {}
    text = requests.get(url).text.splitlines()
    for line in text:
        if ":" in line:
            k, v = line.split(":", 1)
            d[k] = v
    return d

# 2. Load slang dan slur

slang_url = "https://raw.githubusercontent.com/Alfa4026/Skripsi/main/kamus/slang_formal_colon.txt"
slur_url  = "https://raw.githubusercontent.com/Alfa4026/Skripsi/main/kamus/slur_normalization_colon.txt"

slang_dict = load_dict_from_github(slang_url)
slur_dict  = load_dict_from_github(slur_url)

# 3. Fungsi NORMALISASI final

def normalize_slang_and_slur(text):
    new_words = []
    for w in text.split():
        w = w.strip()

        # 1. normalisasi slur (anjg → anjing)
        if w in slur_dict:
            new_words.append(slur_dict[w])
            continue

        # 2. normalisasi slang (gk → tidak, gue → saya)
        if w in slang_dict:
            new_words.append(slang_dict[w])
            continue

        # 3. token tetap
        new_words.append(w)

    return " ".join(new_words)

In [13]:
df = df.copy()
df['normalized_comment'] = df['clean_text'].apply(normalize_slang_and_slur)
df[['Tweet', 'clean_text', 'normalized_comment']]

,Tweet,clean_text,normalized_comment
0,- disaat semua cowok berusaha melacak perhatia...,- disaat semua cowok berusaha melacak perhatia...,- disaat semua cowok berusaha melacak perhatia...
1,RT USER: USER siapa yang telat ngasih tau elu?...,siapa yang telat ngasih tau elu?edan sarap gue...,siapa yang telat ngasih tau elu?edan sarap say...
2,"41. Kadang aku berfikir, kenapa aku tetap perc...","kadang aku berfikir, kenapa aku tetap percaya ...","kadang aku berfikir, kenapa aku tetap percaya ..."
3,USER USER AKU ITU AKU\n\nKU TAU MATAMU SIPIT T...,aku itu aku ku tau matamu sipit tapi diliat da...,aku itu aku ku tau matamu sipit tapi diliat da...
4,USER USER Kaum cebong kapir udah keliatan dong...,kaum cebong kapir udah keliatan dongoknya dari...,kaum cebong kapir udah keliatan dongoknya dari...
...,...,...,...
12877,USER jangan asal ngomong ndasmu. congor lu yg ...,jangan asal ngomong ndasmu. congor lu yg sekat...,jangan asal ngomong ndasmu. congor lu yang sek...
12878,USER Kasur mana enak kunyuk',kasur mana enak kunyuk,kasur mana enak kunyuk
12879,USER Hati hati bisu :( .g\n\nlagi bosan huft \...,hati hati bisu .g lagi bosan huft,hati hati bisu .g lagi bosan huft
12880,USER USER USER USER Bom yang real mudah terdet...,bom yang real mudah terdeteksi bom yang terkub...,bom yang real mudah terdeteksi bom yang terkub...
12881,"USER Mana situ ngasih("": itu cuma foto ya kuti...",mana situ ngasih itu cuma foto ya kutil onta,mana situ ngasih itu cuma foto ya kutil onta

In [14]:
from collections import Counter

all_words = " ".join(df['normalized_comment'].astype(str)).split()
Counter(all_words).most_common(1000)

[('yang', 4885),
 ('tidak', 2718),
 ('dan', 2674),
 ('di', 2668),
 ('saya', 1681),
 ('itu', 1521),
 ('ada', 1292),
 ('ini', 1262),
 ('kalau', 1246),
 ('jadi', 1045),
 ('dengan', 995),
 ('orang', 982),
 ('saja', 895),
 ('tapi', 869),
 ('dari', 819),
 ('untuk', 808),
 ('juga', 798),
 ('bisa', 794),
 ('jokowi', 787),
 ('sama', 784),
 ('kamu', 772),
 ('ingin', 760),
 ('presiden', 758),
 ('aku', 705),
 ('ke', 668),
 ('ya', 666),
 ('dia', 619),
 ('kita', 618),
 ('sudah', 606),
 ('islam', 579),
 ('apa', 562),
 ('agama', 558),
 ('karena', 547),
 ('indonesia', 539),
 ('dalam', 518),
 ('bukan', 517),
 ('pak', 493),
 ('akan', 491),
 ('nya', 474),
 ('lu', 450),
 ('?', 446),
 ('lagi', 443),
 ('si', 442),
 ('tak', 438),
 ('cebong', 436),
 ('.', 425),
 ('pada', 401),
 ('atau', 390),
 ('udah', 388),
 ('mereka', 382),
 ('lebih', 381),
 ('adalah', 377),
 ('-', 368),
 ('banyak', 358),
 (',', 349),
 ('gubernur', 348),
 ('buat', 344),
 ('semua', 341),
 ('cina', 340),
 ('jangan', 339),
 ('banget', 336),
 ('kan', 336),
 ('2019gantipresiden', 335),
 ('rezim', 334),
 ('rakyat', 322),
 ('asing', 318),
 ('punya', 312),
 ('oleh', 312),
 ('masih', 310),
 ('terus', 308),
 ('harus', 306),
 ('negara', 303),
 ('baru', 301),
 ('hanya', 296),
 ('anda', 292),
 ('cuma', 291),
 ('???', 281),
 ('kristen', 273),
 ('kok', 272),
 ('ahok', 267),
 ('pki', 264),
 ('dulu', 264),
 ('pernah', 262),
 ('komunis', 260),
 ('ekonomi', 259),
 ('budaya', 255),
 ('ulama', 252),
 ('pilkada', 251),
 ('anak', 247),
 ('satu', 246),
 ('allah', 245),
 ('menjadi', 244),
 ('tau', 241),
 ('prabowo', 240),
 ('emang', 235),
 ('sih', 235),
 ('malah', 232),
 ('para', 230),
 ('antek', 228),
 ('seperti', 228),
 ('pake', 227),
 ('sebagai', 226),
 ('anjing', 224),
 ('anti', 223),
 ('bikin', 221),
 ('mana', 220),
 ('kafir', 216),
 ('salah', 215),
 ('lah', 215),
 ('hari', 213),
 ('benar', 211),
 ('memang', 205),
 ('dr', 205),
 ('suka', 203),
 ('??', 200),
 ('muslim', 199),
 ('kata', 193),
 ('dah', 193),
 ('bilang', 192),
 ('saat', 192),
 ('tahun', 190),
 ('kau', 189),
 ('sekarang', 189),
 ('siapa', 188),
 ('pasti', 187),
 ('dasar', 187),
 ('onta', 186),
 ('tuh', 184),
 ('2', 183),
 ('biar', 180),
 ('kayak', 178),
 ('kaya', 175),
 ('paling', 172),
 ('nih', 172),
 ('umat', 170),
 ('bom', 169),
 ('baik', 169),
 ('kenapa', 167),
 ('jika', 166),
 ('mungkin', 166),
 ('bani', 165),
 ('lain', 165),
 ('lengserkan', 164),
 ('kerja', 164),
 ('pun', 163),
 ('selalu', 159),
 ('belum', 159),
 ('1', 157),
 ('sampai', 156),
 ('gitu', 156),
 ('tai', 156),
 ('aseng', 155),
 ('masuk', 155),
 ('yahudi', 154),
 ('politik', 153),
 ('kontol', 153),
 ('...', 152),
 ('kampret', 151),
 ('kalian', 151),
 ('boleh', 150),
 ('pemerintah', 149),
 ('goblok', 149),
 ('babi', 149),
 ('pas', 148),
 ('bubarkan', 147),
 ('partai', 146),
 ('dg', 145),
 ('ni', 145),
 ('otak', 144),
 ('mah', 142),
 ('makin', 142),
 ('sipit', 141),
 ('2018', 141),
 ('jgn', 141),
 ('tanpa', 140),
 ('sangat', 140),
 ('katolik', 140),
 ('makan', 138),
 ('dpr', 137),
 ('anies', 137),
 ('kali', 136),
 ('setelah', 135),
 ('hidup', 134),
 ('seorang', 133),
 ('mata', 133),
 ('warga', 131),
 ('bagi', 131),
 ('masa', 130),
 ('kepada', 130),
 ('kami', 129),
 ('manusia', 129),
 ('iya', 128),
 ('d', 128),
 ('eh', 128),
 ('!', 125),
 ('nama', 125),
 ('diri', 123),
 ('kaum', 122),
 ('liat', 122),
 ('dungu', 122),
 ('hoax', 121),
 ('sampe', 121),
 ('kitab', 121),
 ('jawa', 120),
 ('perlu', 120),
 ('tetap', 119),
 ('hati', 119),
 ('sby', 118),
 ('sendiri', 118),
 ('bangsa', 117),
 ('ternyata', 116),
 ('banci', 115),
 ('ikut', 115),
 ('nanti', 115),
 ('ganti', 114),
 ('monyet', 112),
 ('langsung', 112),
 ('nusantara', 111),
 ('masyarakat', 111),
 ('budha', 111),
 ('kpk', 110),
 ('ini,', 110),
 ('cara', 109),
 ('bajingan', 108),
 ('lg', 107),
 ('kek', 107),
 ('sekali', 107),
 ('minta', 107),
 ('ini.', 107),
 ('pemimpin', 107),
 ('padahal', 106),
 ('bahkan', 106),
 ('ngomong', 106),
 ('tolol', 106),
 ('memek', 106),
 ('kasih', 105),
 ('ngentot', 105),
 ('bahwa', 105),
 ('cacat', 105),
 ('4', 105),
 ('usir', 104),
 ('baca', 104),
 ('dapat', 104),
 ('tu', 103),
 ('gimana', 103),
 ('takut', 103),
 ('besar', 103),
 ('china', 102),
 ('3', 101),
 ('dunia', 100),
 ('lalu', 99),
 ('2019', 99),
 ('dukung', 99),
 ('bacot', 98),
 ('tuhan', 97),
 ('negeri', 97),
 ('agar', 97),
 ('ku', 96),
 ('semoga', 96),
 ('jelas', 96),
 ('cinta', 96),
 ('suci', 95),
 ('secara', 95),
 ('kembali', 95),
 ('calon', 95),
 ('ya?', 95),
 ('isu', 95),
 ('..', 94),
 ('waktu', 94),
 ('hukum', 93),
 ('mulai', 93),
 ('bego', 92),
 ('gini', 92),
 ('pengen', 92),
 ('soal', 92),
 ('penista', 92),
 ('lama', 92),
 ('g', 91),
 ('maka', 91),
 ('bahasa', 91),
 ('sok', 91),
 ('jalan', 90),
 ('ia', 90),
 ('telah', 89),
 ('semakin', 89),
 ('wakil', 89),
 ('pd', 89),
 ('dong', 89),
 ('buta', 89),
 ('rumah', 89),
 ('hal', 88),
 ('kunyuk', 88),
 ('ketika', 87),
 ('namanya', 87),
 ('hindu', 87),
 ('coba', 86),
 ('uang', 86),
 ('tempat', 86),
 ('beli', 86),
 ('beda', 84),
 ('skrg', 84),
 ('bapak', 84),
 ('naik', 84),
 ('selama', 84),
 ('apakah', 84),
 ('kota', 83),
 ('cari', 83),
 ('sekolah', 83),
 ('sebelum', 83),
 ('karna', 83),
 ('kena', 82),
 ('tahu', 82),
 ('korupsi', 82),
 ('kasus', 82),
 ('atas', 82),
 ('swt', 82),
 ('berani', 82),
 ('begitu', 82),
 ('ri', 81),
 ('pakai', 81),
 ('membuat', 81),
 ('biasa', 80),
 ('katanya', 80),
 ('idiot', 80),
 ('lihat', 79),
 ('setan', 79),
 ('luar', 79),
 ('temen', 79),
 ('tentang', 79),
 ('apalagi', 78),
 ('a', 78),
 ('jakarta', 78),
 ('hasil', 78),
 ('makanya', 77),
 ('islam,', 77),
 ('sampah', 77),
 ('rasa', 77),
 ('main', 77),
 ('ah', 77),
 ('paham', 77),
 ('belajar', 76),
 ('tka', 76),
 ('brengsek', 76),
 ('harga', 76),
 ('spt', 76),
 ('pilih', 76),
 ('masalah', 76),
 ('percaya', 75),
 ('sejak', 75),
 ('dua', 75),
 ('bersama', 75),
 ('berarti', 75),
 ('melihat', 75),
 ('ama', 74),
 ('selamat', 74),
 ('munafik', 74),
 ('gila', 74),
 ('beberapa', 73),
 ('amat', 73),
 ('teroris', 73),
 ('terlalu', 73),
 ('kecil', 73),
 ('suara', 72),
 ('polisi', 72),
 ('indonesia.', 71),
 ('berita', 71),
 ('mas', 71),
 ('beliau', 71),
 ('akun', 71),
 ('bodo', 71),
 ('bakal', 71),
 ('demi', 71),
 ('dki', 71),
 ('wkwk', 70),
 ('jaman', 70),
 ('deh', 70),
 ('kurang', 70),
 ('proyek', 70),
 ('pendukung', 70),
 ('pro', 69),
 ('tersebut', 69),
 ('cukup', 69),
 ('sebuah', 69),
 ('the', 68),
 ('maju', 68),
 ('mati', 68),
 ('penting', 68),
 ('sedang', 67),
 ('merasa', 66),
 ('jawab', 66),
 ('era', 66),
 ('!!!', 66),
 ('sandi', 66),
 ('serta', 66),
 ('islam.', 66),
 ('ayo', 66),
 ('kepala', 65),
 ('lupa', 65),
 ('ketua', 65),
 ('mendukung', 65),
 ('siap', 64),
 ('keluar', 64),
 ('demo', 64),
 ('bang', 64),
 ('duit', 64),
 ('pks', 64),
 ('keluarga', 64),
 ('asal', 64),
 ('enak', 63),
 ('susah', 63),
 ('la', 63),
 ('setiap', 63),
 ('mu', 63),
 ('mundur', 63),
 ('itu.', 63),
 ('orang-orang', 63),
 ('akhirnya', 63),
 ('malu', 62),
 ('nabi', 62),
 ('terhadap', 62),
 ('!!', 62),
 ('aja.', 62),
 ('itu,', 62),
 ('uu', 62),
 ('s', 61),
 ('bicara', 61),
 ('menurut', 61),
 ('sering', 61),
 ('pembangunan', 61),
 ('ibu', 61),
 ('arab', 61),
 ('aman', 60),
 ('agama,', 60),
 ('usah', 60),
 ('fiksi', 60),
 ('kalah', 60),
 ('congor', 60),
 ('i', 60),
 ('nkri', 60),
 ('jauh', 60),
 ('mampu', 60),
 ('bagaimana', 60),
 ('damai', 59),
 ('bulan', 59),
 ('sini', 59),
 ('zaman', 59),
 ('tukang', 59),
 ('termasuk', 59),
 ('hahaha', 59),
 ('lbh', 59),
 ('jual', 59),
 ('rejim', 59),
 ('nonton', 59),
 ('teriak', 59),
 ('x', 58),
 ('dimana', 58),
 ('film', 58),
 ('balik', 58),
 ('wkwkwk', 58),
 ('ya,', 58),
 ('bodoh', 58),
 ('yakin', 58),
 ('bila', 58),
 ('kelas', 58),
 ('freeport', 58),
 ('bangsat', 58),
 ('memiliki', 57),
 ('gereja', 57),
 ('an', 57),
 ('bertemu', 57),
 ('budek', 57),
 ('ente', 56),
 ('dilakukan', 56),
 ('menang', 56),
 ('muhammad', 56),
 ('ma', 56),
 ('depan', 55),
 ('tradisi', 55),
 ('mari', 55),
 ('pertama', 55),
 ('ya.', 55),
 ('7', 55),
 ('butuh', 55),
 ('mampus', 55),
 ('disebut', 55),
 ('terjadi', 54),
 ('indonesia,', 54),
 ('sakit', 54),
 ('betul', 54),
 ('daripada', 54),
 ('5', 54),
 ('lgbt', 54),
 ('agama.', 54),
 ('mulu', 54),
 ('sarap', 53),
 ('nak', 53),
 ('sejarah', 53),
 ('pemilihan', 53),
 ('daerah', 53),
 ('bawa', 53),
 ('saling', 53),
 ('pilpres', 53),
 ('hak', 53),
 ('media', 53),
 ('foto', 53),
 ('namun', 53),
 ('saham', 53),
 ('joko', 52),
 ('itulah', 52),
 ('iblis', 52),
 ('cocot', 52),
 ('najis', 52),
 ('titit', 52),
 ('buaya', 52),
 ('doang', 52),
 ('bau', 52),
 ('macam', 52),
 ('fitnah', 52),
 ('dibilang', 52),
 ('nah', 51),
 ('pemerintahan', 51),
 ('guru', 51),
 ('edan', 51),
 ('tokoh', 51),
 ('video', 51),
 ('tanya', 51),
 ('knp', 51),
 ('merupakan', 51),
 ('sebut', 51),
 ('artinya', 51),
 ('mending', 51),
 ('melakukan', 51),
 ('anggota', 51),
 ('memilih', 50),
 ('sma', 50),
 ('acara', 50),
 ('hrs', 50),
 ('barat', 50),
 ('banten', 50),
 ('rp', 50),
 ('ngapain', 50),
 ('menteri', 50),
 ('kapir', 49),
 ('keras', 49),
 ('bukti', 49),
 ('ngaku', 49),
 ('u', 49),
 ('ajaran', 49),
 ('msh', 49),
 ('sebenarnya', 49),
 ('malam', 49),
 ('ganyang', 49),
 ('diktator', 49),
 ('gembel', 48),
 ('bangke', 48),
 ('om', 48),
 ('kampang', 48),
 ('bkn', 48),
 ('10', 48),
 ('justru', 48),
 ('as', 48),
 ('sambil', 47),
 ('tinggi', 47),
 ('bloon', 47),
 ('cerita', 47),
 ('kapan', 47),
 ('bisu', 47),
 ('mulut', 47),
 ('muka', 47),
 ('dpt', 47),
 ('kacung', 47),
 ('selain', 47),
 ('setuju', 47),
 ('tolong', 47),
 ('nu', 47),
 ('pagi', 47),
 ('bencong', 47),
 ('bandara', 46),
 ('muncul', 46),
 ('maaf', 46),
 ('menolak', 46),
 ('cm', 46),
 ('haha', 46),
 ('w', 46),
 ('sayang', 46),
 ('tangan', 46),
 ('sesuai', 46),
 ('100', 46),
 ('kebijakan', 45),
 ('mantan', 45),
 ('wanita', 45),
 ('al', 45),
 ('korban', 45),
 ('biadab', 45),
 ('tiap', 45),
 ('tinggal', 45),
 ('pancasila', 45),
 ('2.', 45),
 ('1.', 45),
 ('taplak', 44),
 ('selesai', 44),
 ('lewat', 44),
 ('pinter', 44),
 ('tim', 44),
 ('dongo', 44),
 ('asu', 44),
 ('bunuh', 44),
 ('mrk', 44),
 ('janji', 44),
 ('sd', 44),
 ('kuat', 44),
 ('emg', 44),
 ('jokowi.', 44),
 ('abis', 44),
 ('tengah', 43),
 ('habis', 43),
 ('sadar', 43),
 ('tetep', 43),
 ('desa', 43),
 ('kemarin', 43),
 ('bumi', 43),
 ('barang', 43),
 ('jongos', 43),
 ('dll', 43),
 ('tanah', 43),
 ('jokowi,', 43),
 ('sinting', 43),
 ('jablay', 42),
 ('lawan', 42),
 ('bangsad', 42),
 ('benci', 42),
 ('apapun', 42),
 ('ilmu', 42),
 ('kebanyakan', 42),
 ('dana', 42),
 ('melalui', 42),
 ('pribumi', 42),
 ('kira', 42),
 ('turunkan', 42),
 ('tua', 42),
 ('segera', 42),
 ('bagus', 42),
 ('tetapi', 42),
 ('hingga', 42),
 ('bank', 41),
 ('apa?', 41),
 ('klu', 41),
 ('utang', 41),
 ('pencitraan', 41),
 ('gerakan', 41),
 ('mayoritas', 41),
 ('jkw', 41),
 ('tentu', 41),
 ('perempuan', 41),
 ('gagal', 41),
 ('buang', 41),
 ('baduy', 41),
 ('asing.', 41),
 ('lucu', 41),
 ('antara', 41),
 ('otaknya', 41),
 ('in', 41),
 ('aksi', 41),
 ('awal', 40),
 ('ngewe', 40),
 ('produk', 40),
 ('kak', 40),
 ('kelakuan', 40),
 ('diam', 40),
 ('sibuk', 40),
 ('berbagai', 40),
 ('pusat', 40),
 ('air', 40),
 ('supaya', 40),
 ('suruh', 40),
 ('terima', 40),
 ('user', 40),
 ('wah', 40),
 ('picek', 40),
 ('nusantara,', 40),
 ('wajib', 40),
 ('rohingya', 40),
 ('mikir', 40),
 ('bela', 40),
 ('smp', 40),
 ('milik', 40),
 ('kelompok', 40),
 ('oh', 40),
 ('gaji', 40),
 ('kadang', 39),
 ('nanya', 39),
 ('impor', 39),
 ('lahir', 39),
 ('ntar', 39),
 ('k', 39),
 ('aja,', 39),
 ('begini', 39),
 ('sana', 39),
 ('pasangan', 39),
 ('ngerti', 39),
 ('orang2', 39),
 ('lagi,', 39),
 ('tni', 39),
 ('kpd', 39),
 ('harusnya', 39),
 ('alias', 39),
 ('tadi', 39),
 ('gus', 39),
 ('bagian', 39),
 ('nasional', 39),
 ('cantik', 39),
 ('bangkai', 39),
 ('lain.', 39),
 ('non', 39),
 ('udik', 39),
 ('memberikan', 39),
 ('jam', 38),
 ('cuman', 38),
 ('bolot', 38),
 ('senang', 38),
 ('koruptor', 38),
 ('minum', 38),
 ('contoh', 38),
 ('badan', 38),
 ('program', 38),
 ('sehingga', 38),
 ('segala', 38),
 ('21', 38),
 ('sebabaduy2018', 38),
 ('giliran', 38),
 ('lagi.', 38),
 ('penuh', 38),
 ('geblek', 38),
 ('seluruh', 38),
 ('papua', 38),
 ('kan?', 38),
 ('bin', 38),
 ('marah', 38),
 ('khusus', 37),
 ('ttg', 37),
 ('gede', 37),
 ('hina', 37),
 ('dekat', 37),
 ('tidur', 37),
 ('golongan', 37),
 ('mudah', 37),
 ('b', 37),
 ('pihak', 37),
 ('jamban', 37),
 ('kristen,', 37),
 ('m', 37),
 ('keturunan', 37),
 ('apaan', 37),
 ('adat', 37),
 ('berapa', 37),
 ('yah', 37),
 ('disini', 37),
 ('anies-sandi', 37),
 ('salam', 37),
 ('hampir', 37),
 ('mirip', 37),
 ('cewe', 37),
 ('dukungan', 36),
 ('kaga', 36),
 ('april', 36),
 ('umum', 36),
 ('urusan', 36),
 ('walaupun', 36),
 ('tpi', 36),
 ('sistem', 36),
 ('putih', 36),
 ('jijik', 36),
 ('suatu', 36),
 ('tki', 36),
 ('hancur', 36),
 ('isinya', 36),
 ('sukses', 36),
 ('eek', 36),
 ('terbukti', 36),
 ('menghina', 36),
 ('bu', 35),
 ('kyk', 35),
 ('on', 35),
 ('mengatakan', 35),
 ('bung', 35),
 ('to', 35),
 ('loh', 35),
 ('capres', 35),
 ('bpk', 35),
 ('sosial', 35),
 ('quran', 35),
 ('membela', 35),
 ('pulang', 35),
 ('dll.', 35),
 ('tionghoa', 35),
 ('periode', 35),
 ('yaa', 35),
 ('karya', 35),
 ('gara', 35),
 ('p', 35),
 ('anaknya', 35),
 ('rugi', 35),
 ('keliatan', 34),
 ('widodo', 34),
 ('yaitu', 34),
 ('asli', 34),
 ('milih', 34),
 ('sedikit', 34),
 ('no', 34),
 ('yuk', 34),
 ('ha', 34),
 ('ingat', 34),
 ('tolak', 34),
 ('kampungan', 34),
 ('kenal', 34),
 ('sabtu', 34),
 ('buka', 34),
 ('ekonomi,', 34),
 ('sara', 34),
 ('gaya', 34),
 ('jabar', 34),
 ('keparat', 34),
 ('baju', 34),
 ('agak', 34),
 ('busuk', 34),
 ('biasanya', 34),
 ('20', 34),
 ('bangun', 34),
 ('terlihat', 33),
 ('bayar', 33),
 ('kucing', 33),
 ('pdip', 33),
 ('gt', 33),
 ('culun', 33),
 ('saracen', 33),
 ('menggunakan', 33),
 ('ambil', 33),
 ('alasan', 33),
 ('semuanya', 33),
 ('lebak', 33),
 ('cewek', 33),
 ('isi', 33),
 ('data', 33),
 ('terkait', 33),
 ('kader', 33),
 ('cepat', 33),
 ('lesbi', 33),
 ('ayat', 33),
 ('bangga', 33),
 ('nyata', 32),
 ('kayaknya', 32),
 ('6', 32),
 ('tingkat', 32),
 ('sesama', 32),
 ('doi', 32),
 ('ngatain', 32),
 ('seba', 32),
 ('byk', 32),
 ('ngakak', 32),
 ('wong', 32),
 ('juta', 32),
 ('dapet', 32),
 ('so', 32),
 ('buku', 32),
 ('maho', 32),
 ('kafir,', 32),
 ('smua', 32),
 ('proses', 32),
 ('berusaha', 31),
 ('deklarasi', 31),
 ('heran', 31),
 ('and', 31),
 ('ketemu', 31),
 ('sedih', 31),
 ('ngerasa', 31),
 ('plongo', 31),
 ('perang', 31),
 ('hutang', 31),
 ('tenang', 31),
 ('situ', 31),
 ('sontoloyo', 31),
 ('dilanjutkan', 31),
 ('tgb', 31),
 ('walau', 31),
 ('sekalian', 31),
 ('myanmar', 31),
 ('pula', 31),
 ('mohon', 31),
 ('dikit', 31),
 ('abang', 31),
 ('muda', 31),
 ('untung', 31),
 ('layak', 31),
 ('adlh', 31),
 ('katolik.', 31),
 ('pikir', 31),
 ('luh', 31),
 ('bantu', 31),
 ('prestasi', 31),
 ('bukannya', 31),
 ('cowok', 30),
 ('cowo', 30),
 ('nete', 30),
 ('debat', 30),
 ('istilah', 30),
 ('2019presidenbaru', 30),
 ('pintar', 30),
 ('presiden.', 30),
 ('pantat', 30),
 ('istana', 30),
 ('bro', 30),
 ('asing,', 30),
 ('kantor', 30),
 ('thn', 30),
 ('e', 30),
 ('dikasih', 30),
 ('merusak', 30),
 ('nyinyir', 30),
 ('datang', 30),
 ('ka', 30),
 ('sendiri.', 30),
 ('komunis.', 30),
 ('kencing', 29),
 ('sementara', 29),
 ('maupun', 29),
 ('kini', 29),
 ('nasi', 29),
 ('besok', 29),
 ('ampe', 29),
 ('turun', 29),
 ('fpi', 29),
 ('malaysia', 29),
 ('meja', 29),
 ('melawan', 29),
 ('hebat', 29),
 ('membangun', 29),
 ('aneh', 29),
 ('kampanye', 29),
 ('pejabat', 29),
 ('cc', 29),
 ('kecuali', 29),
 ('haram', 29),
 ('kacrut', 29),
 ('mo', 29),
 ('semangat', 29),
 ('bawah', 29),
 ('kritik', 29),
 ('kekuasaan', 29),
 ('kedua', 29),
 ('fakta', 29),
 ('mahal', 29),
 ('kemaren', 29),
 ('mmg', 29),
 ('lelaki', 29),
 ('diem', 29),
 ('mengapa', 29),
 ('timur', 29),
 ('peduli', 29),
 ('gelar', 29),
 ('ala', 29),
 ('sebab', 29),
 ('ustad', 29),
 ('elo', 28),
 ('tambah', 28),
 ('utama', 28),
 ('modal', 28),
 ('nyari', 28),
 ('kaki', 28),
 ('entah', 28),
 ('terkutuk', 28),
 ('amin', 28),
 ('cina.', 28),
 ('kepentingan', 28),
 ('y', 28),
 ('ada.', 28),
 ('bentuk', 28),
 ('wahidin', 28),
 ('juga.', 28),
 ('retweet', 28),
 ('o', 28),
 ('kehidupan', 28),
 ('berharap', 28),
 ('212', 28),
 ('pasar', 28),
 ('korea', 28),
 ('bocah', 28),
 ('presiden,', 28),
 ('bebas', 28),
 ('ayam', 28),
 ('nasib', 28),
 ('51', 28),
 ('sang', 28),
 ('otoriter', 28),
 ('pilihan', 28),
 ('denger', 28),
 ('keren', 28),
 ('lagu', 28),
 ('9', 28),
 ('98', 27),
 ('lokal', 27)]

In [21]:
import requests

def load_set_from_github(url):
    return {line.strip() for line in requests.get(url).text.splitlines()}

stopwords_url = "https://raw.githubusercontent.com/Alfa4026/Skripsi/main/kamus/stopwords_colon.txt"
removal_url   = "https://raw.githubusercontent.com/Alfa4026/Skripsi/main/kamus/removal_tokens_colon.txt"

stopwords_set  = load_set_from_github(stopwords_url)
removal_tokens = load_set_from_github(removal_url)

In [22]:
def clean_stopword(text):
    words = text.split()
    cleaned = []

    for w in words:

        # 1. Hapus token noise
        if w in removal_tokens:
            continue

        # 2. Hapus stopword
        if w in stopwords_set:
            continue

        cleaned.append(w)

    return " ".join(cleaned)

In [23]:
df = df.copy()

df['stopword_clean'] = df['normalized_comment'].apply(clean_stopword)

df[['Tweet', 'clean_text', 'normalized_comment', 'stopword_clean']]

,Tweet,clean_text,normalized_comment,stopword_clean
0,- disaat semua cowok berusaha melacak perhatia...,- disaat semua cowok berusaha melacak perhatia...,- disaat semua cowok berusaha melacak perhatia...,disaat cowok berusaha melacak perhatian gue. k...
1,RT USER: USER siapa yang telat ngasih tau elu?...,siapa yang telat ngasih tau elu?edan sarap gue...,siapa yang telat ngasih tau elu?edan sarap say...,siapa telat ngasih tau elu?edan sarap saya ber...
2,"41. Kadang aku berfikir, kenapa aku tetap perc...","kadang aku berfikir, kenapa aku tetap percaya ...","kadang aku berfikir, kenapa aku tetap percaya ...","kadang aku berfikir, kenapa aku tetap percaya ..."
3,USER USER AKU ITU AKU\n\nKU TAU MATAMU SIPIT T...,aku itu aku ku tau matamu sipit tapi diliat da...,aku itu aku ku tau matamu sipit tapi diliat da...,aku aku tau matamu sipit tapi diliat mana aku
4,USER USER Kaum cebong kapir udah keliatan dong...,kaum cebong kapir udah keliatan dongoknya dari...,kaum cebong kapir udah keliatan dongoknya dari...,kaum cebong kapir udah keliatan dongoknya awal...
...,...,...,...,...
12877,USER jangan asal ngomong ndasmu. congor lu yg ...,jangan asal ngomong ndasmu. congor lu yg sekat...,jangan asal ngomong ndasmu. congor lu yang sek...,jangan asal ngomong ndasmu. congor lu sekate2 ...
12878,USER Kasur mana enak kunyuk',kasur mana enak kunyuk,kasur mana enak kunyuk,kasur mana enak kunyuk
12879,USER Hati hati bisu :( .g\n\nlagi bosan huft \...,hati hati bisu .g lagi bosan huft,hati hati bisu .g lagi bosan huft,hati hati bisu .g bosan huft
12880,USER USER USER USER Bom yang real mudah terdet...,bom yang real mudah terdeteksi bom yang terkub...,bom yang real mudah terdeteksi bom yang terkub...,bom real mudah terdeteksi bom terkubur suatu s...
12881,"USER Mana situ ngasih("": itu cuma foto ya kuti...",mana situ ngasih itu cuma foto ya kutil onta,mana situ ngasih itu cuma foto ya kutil onta,mana situ ngasih foto kutil onta

In [18]:
df

,Tweet,HS,Abusive,HS_Individual,HS_Group,HS_Religion,HS_Race,HS_Physical,HS_Gender,HS_Other,HS_Weak,HS_Moderate,HS_Strong,clean_text,normalized_comment,stopword_clean
0,- disaat semua cowok berusaha melacak perhatia...,1,1,1,0,0,0,0,0,1,1,0,0,- disaat semua cowok berusaha melacak perhatia...,- disaat semua cowok berusaha melacak perhatia...,disaat cowok berusaha melacak perhatian gue. k...
1,RT USER: USER siapa yang telat ngasih tau elu?...,0,1,0,0,0,0,0,0,0,0,0,0,siapa yang telat ngasih tau elu?edan sarap gue...,siapa yang telat ngasih tau elu?edan sarap say...,siapa telat ngasih tau elu?edan sarap saya ber...
2,"41. Kadang aku berfikir, kenapa aku tetap perc...",0,0,0,0,0,0,0,0,0,0,0,0,"kadang aku berfikir, kenapa aku tetap percaya ...","kadang aku berfikir, kenapa aku tetap percaya ...","kadang aku berfikir, kenapa aku tetap percaya ..."
3,USER USER AKU ITU AKU\n\nKU TAU MATAMU SIPIT T...,0,0,0,0,0,0,0,0,0,0,0,0,aku itu aku ku tau matamu sipit tapi diliat da...,aku itu aku ku tau matamu sipit tapi diliat da...,aku aku tau matamu sipit tapi diliat mana aku
4,USER USER Kaum cebong kapir udah keliatan dong...,1,1,0,1,1,0,0,0,0,0,1,0,kaum cebong kapir udah keliatan dongoknya dari...,kaum cebong kapir udah keliatan dongoknya dari...,kaum cebong kapir udah keliatan dongoknya awal...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12877,USER jangan asal ngomong ndasmu. congor lu yg ...,1,1,1,0,0,0,1,0,0,1,0,0,jangan asal ngomong ndasmu. congor lu yg sekat...,jangan asal ngomong ndasmu. congor lu yang sek...,jangan asal ngomong ndasmu. congor lu sekate2 ...
12878,USER Kasur mana enak kunyuk',0,1,0,0,0,0,0,0,0,0,0,0,kasur mana enak kunyuk,kasur mana enak kunyuk,kasur mana enak kunyuk
12879,USER Hati hati bisu :( .g\n\nlagi bosan huft \...,0,0,0,0,0,0,0,0,0,0,0,0,hati hati bisu .g lagi bosan huft,hati hati bisu .g lagi bosan huft,hati hati bisu .g bosan huft
12880,USER USER USER USER Bom yang real mudah terdet...,0,0,0,0,0,0,0,0,0,0,0,0,bom yang real mudah terdeteksi bom yang terkub...,bom yang real mudah terdeteksi bom yang terkub...,bom real mudah terdeteksi bom terkubur suatu s...
12881,"USER Mana situ ngasih("": itu cuma foto ya kuti...",1,1,1,0,0,0,0,0,1,1,0,0,mana situ ngasih itu cuma foto ya kutil onta,mana situ ngasih itu cuma foto ya kutil onta,mana situ ngasih foto kutil onta

In [19]:
# df.to_csv("hatespeech_preprocessed.csv", index=False)

In [24]:
df["stopword_clean"].str.split(expand=True).stack().value_counts().head(300)

tidak         2718
saya          1681
ada           1292
kalau         1246
orang          982
              ...
dki             71
indonesia.      71
berita          71
bakal           71
beliau          71
Name: count, Length: 300, dtype: int64