In [1]:
# %pip install transformers

In [2]:
from transformers import AutoTokenizer

MODEL_NAME = "indobenchmark/indobert-base-p1"
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

In [3]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/Alfa4026/Skripsi/main/dataset/hatespeech_preprocessed.csv")
df

,Tweet,HS,Abusive,HS_Individual,HS_Group,HS_Religion,HS_Race,HS_Physical,HS_Gender,HS_Other,HS_Weak,HS_Moderate,HS_Strong,clean_text,normalized_comment,stopword_clean
0,- disaat semua cowok berusaha melacak perhatia...,1,1,1,0,0,0,0,0,1,1,0,0,- disaat semua cowok berusaha melacak perhatia...,- disaat semua cowok berusaha melacak perhatia...,disaat cowok berusaha melacak perhatian gue. k...
1,RT USER: USER siapa yang telat ngasih tau elu?...,0,1,0,0,0,0,0,0,0,0,0,0,siapa yang telat ngasih tau elu?edan sarap gue...,siapa yang telat ngasih tau elu?edan sarap say...,siapa telat ngasih tau elu?edan sarap saya ber...
2,"41. Kadang aku berfikir, kenapa aku tetap perc...",0,0,0,0,0,0,0,0,0,0,0,0,"kadang aku berfikir, kenapa aku tetap percaya ...","kadang aku berfikir, kenapa aku tetap percaya ...","kadang aku berfikir, kenapa aku tetap percaya ..."
3,USER USER AKU ITU AKU\n\nKU TAU MATAMU SIPIT T...,0,0,0,0,0,0,0,0,0,0,0,0,aku itu aku ku tau matamu sipit tapi diliat da...,aku itu aku ku tau matamu sipit tapi diliat da...,aku aku tau matamu sipit tapi diliat mana aku
4,USER USER Kaum cebong kapir udah keliatan dong...,1,1,0,1,1,0,0,0,0,0,1,0,kaum cebong kapir udah keliatan dongoknya dari...,kaum cebong kapir udah keliatan dongoknya dari...,kaum cebong kapir udah keliatan dongoknya awal...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12877,USER jangan asal ngomong ndasmu. congor lu yg ...,1,1,1,0,0,0,1,0,0,1,0,0,jangan asal ngomong ndasmu. congor lu yg sekat...,jangan asal ngomong ndasmu. congor lu yang sek...,jangan asal ngomong ndasmu. congor lu sekate2 ...
12878,USER Kasur mana enak kunyuk',0,1,0,0,0,0,0,0,0,0,0,0,kasur mana enak kunyuk,kasur mana enak kunyuk,kasur mana enak kunyuk
12879,USER Hati hati bisu :( .g\n\nlagi bosan huft \...,0,0,0,0,0,0,0,0,0,0,0,0,hati hati bisu .g lagi bosan huft,hati hati bisu .g lagi bosan huft,hati hati bisu .g bosan huft
12880,USER USER USER USER Bom yang real mudah terdet...,0,0,0,0,0,0,0,0,0,0,0,0,bom yang real mudah terdeteksi bom yang terkub...,bom yang real mudah terdeteksi bom yang terkub...,bom real mudah terdeteksi bom terkubur suatu s...
12881,"USER Mana situ ngasih("": itu cuma foto ya kuti...",1,1,1,0,0,0,0,0,1,1,0,0,mana situ ngasih itu cuma foto ya kutil onta,mana situ ngasih itu cuma foto ya kutil onta,mana situ ngasih foto kutil onta

In [4]:
label_cols = [
    "HS",
    "Abusive",
    "HS_Individual",
    "HS_Group",
    "HS_Religion",
    "HS_Race",
    "HS_Physical",
    "HS_Gender",
    "HS_Other",
    "HS_Weak",
    "HS_Moderate",
    "HS_Strong"
]

X = df["stopword_clean"].values
Y = df[label_cols].astype(int).values

In [5]:
texts = df["stopword_clean"].astype(str).tolist()

In [6]:
MAX_LEN = 128

encodings = tokenizer(
    texts,
    truncation=True,
    padding="max_length",
    max_length=MAX_LEN,
    return_attention_mask=True,
)

In [7]:
import pandas as pd

df_tokens = pd.DataFrame({
    "input_ids": encodings["input_ids"],
    "attention_mask": encodings["attention_mask"]
})

# Gabungkan label
df_final = pd.concat([df_tokens, df[label_cols].reset_index(drop=True)], axis=1)

df_final.head()

,input_ids,attention_mask,HS,Abusive,HS_Individual,HS_Group,HS_Religion,HS_Race,HS_Physical,HS_Gender,HS_Other,HS_Weak,HS_Moderate,HS_Strong
0,"[2, 9546, 5713, 2390, 14011, 2598, 2526, 30470...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",1,1,1,0,0,0,0,0,1,1,0,0
1,"[2, 1545, 12207, 13710, 2088, 25998, 30477, 28...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",0,1,0,0,0,0,0,0,0,0,0,0
2,"[2, 3597, 304, 7254, 30468, 2124, 304, 830, 21...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",0,0,0,0,0,0,0,0,0,0,0,0
3,"[2, 304, 304, 2088, 24440, 2885, 47, 469, 2773...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, ...",0,0,0,0,0,0,0,0,0,0,0,0
4,"[2, 2519, 28731, 225, 1012, 72, 2137, 16666, 3...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",1,1,0,1,1,0,0,0,0,0,1,0

In [ ]:
# df_final.to_pickle("hatespeech_indobert_tokenized.pkl")

In [9]:
label_cols = [
    "HS",
    "Abusive",
    "HS_Individual",
    "HS_Group",
    "HS_Religion",
    "HS_Race",
    "HS_Physical",
    "HS_Gender",
    "HS_Other",
    "HS_Weak",
    "HS_Moderate",
    "HS_Strong"
]

len(label_cols)

12